crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path, include
from leads.views import LandingPageView,registerPage ,loginPage , logoutUser 
from agents.views import  dashboard , agentdashboard ,configuration




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView, name='landing-page'),
    path('dashboard/', dashboard , name='dashboard'),
    path('agentdashboard/', agentdashboard , name='agent-dashboard'),
    path('config/', configuration , name='config'),
    path('leads/', include(('leads.urls','leads'),namespace="leads")),
    path('agents/',include(('agents.urls','agents'),namespace="agents")),
    path('signup/',registerPage, name='signup'),
    path('login/', loginPage,name='login'),
    path('logout/', logoutUser,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import customer_comm, customer_list, lead_list, lead_detail,lead_create,lead_update,lead_create,lead_update , lead_delete 
from .helpers.pdf import GeneratePdf ,helper
from .helpers.email import  send_my_mail

from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib import admin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_names = "leads"

urlpatterns = [
    path('', lead_list, name='lead-list'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/genratequoation/',GeneratePdf.as_view(), name='pdf'),
    path('<int:pk>/helper/', helper , name='help'),
    path('<int:pk>/delete/', lead_delete , name='lead-delete'),
    path('<int:pk>/email', send_my_mail, name='sendEmail'),
    path('create/',lead_create, name='lead-create'),
    path('cust', customer_list , name='customers-list'),
    path('<int:pk>/cust_comm', customer_comm , name='customers-comm'),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL ,document_root = settings.STATIC_ROOT)

leads/forms.py
from dataclasses import field
from random import choices
from colorama import Style
from django.forms import ModelForm

from customers.models import Customer_communication
from .models import Lead, lead_activity , lead_communication,quotation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2' ]

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'agent',
            'size',
            'location',
            'phone_number',
            'designation',
            'email',
            'source',
            'stage',
            'status',
            'pincode',
        )
        widgets = {
            'email' : forms.EmailInput(attrs={'id' : 'email' , 'class':"box" , 'style':'left: 100px;top: 400px;', 'placeholder' : 'Emai**'}),
            'phone_number' : forms.NumberInput(attrs={'class':"box" , 'style':'left: 781px;top: 400px;', 'placeholder' : 'Phone Number**' , 'max_length': '10'}),
            'first_name' : forms.TextInput(attrs={'class':'box', 'style':'top: 220px; left: 101px;', 'placeholder' : 'First Name'}),
            'last_name': forms.TextInput(attrs={'class':"box", 'style':'left: 781px; top: 220px;','placeholder' : 'Last Name'}),
            'agent' : forms.Select(choices=['test'],attrs={'class':'box', 'style':'top: 320px; left: 101px;', 'placeholder' : 'First Name'}),
            'size': forms.TextInput(attrs={'class':"box" , 'style':'left: 100px;top: 670px;'}),
            'location': forms.TextInput(attrs={'class':"box" , 'style':'left: 100px;top: 490px;'}),
            'designation': forms.TextInput(attrs={'class':"box" , 'style':'left: 781px;top: 670px;'}),
            'source': forms.TextInput(attrs={'class':"box" , 'style':'left: 100px;top: 580px;'}),
            'stage': forms.TextInput(attrs={'class':"box" , 'style':'left: 781px;top: 580px;'}),
            'status': forms.TextInput(attrs={'class':"box", 'style':'left: 781px;top: 310px;'}),
            'pincode': forms.TextInput(attrs={'class':"box", 'style':'left: 781px;top: 490px;'}),
        }

class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'is_converted' ,
        )

class Lead_communication_form(forms.ModelForm):
    class Meta:
        model = lead_communication 
        fields = (
            'message',
            ) 

        widgets = {
            'message' : forms.Textarea(attrs={ 'id' : 'message', 'placeholder': 'Your Conversation here*', 'class' : 'box', 'cols': '50', 'rows': '5' }),
        }



class Lead_activity_form(forms.ModelForm):
    class Meta:
        model = lead_activity
        fields = (
            'activity_name',
            'scheduled_date',
            'actual_date',
            'demo_status',
            )   
        widgets = {
            'scheduled_date' : forms.DateInput(attrs={'type' :"date"}),
            'activity_name' : forms.Select(choices=['ACTIVITY_CHOICES']),
            'actual_date' : forms.DateInput(attrs={'type' :"date"}),
            'demo_status' : forms.Select(choices=['STATUS_CHOICE']), 
        }




class pdf_form(forms.ModelForm):
    class Meta:
        model = quotation
        fields = (
            'lead_id',
            'quotation_file_name',
            'Quantity',
            'product_id',
            'price_offered',
            )   
        widgets = {
            'lead_id' : forms.HiddenInput(attrs={'id' : 'lead_id'}),
            'price_offered': forms.TextInput(attrs={'id':"p_id"}),
        }


class Customer_communication_form(forms.ModelForm):
    class Meta:
        model = Customer_communication
        fields = (
            'message',
            )
        widgets = {
            'message' : forms.Textarea(attrs={ 'id' : 'message', 'placeholder': 'Your Conversation here*', 'class' : 'box', 'cols': '50', 'rows': '5' }),
        }

leads/views.py
from django.core.mail import send_mail
from urllib.request import Request
from django.shortcuts import get_object_or_404, render, redirect, reverse 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,CreateView,UpdateView,DeleteView
from customers.models import Customer
from customers.forms import customer_form
from .forms import  *
from django.http import HttpResponse, JsonResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from .models import *
from .forms import CreateUserForm
from .decorators import unauthenticated_user, allowed_users, admin_only
from agents.models import agent
import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
from .resources import LeadResource
from tablib import Dataset
import speech_recognition as sr
from leads.helpers import pdf


@receiver(post_save, sender=User)
def handle_new_job(sender, **kwargs):
    if kwargs.get('created', False):
        user = kwargs.get('instance')
        g = Group.objects.get(name='agent')
        user.groups.add(g)


def registerPage(request):
    if request.user.is_authenticated:
        return redirect('landing-page')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return redirect('login')
        context = {'form':form}
        return render(request, 'registration/signup.html', context)

@unauthenticated_user
def loginPage(request):
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('landing-page')
			else:
				messages.info(request, 'Username OR password is incorrect')

		return render(request, 'registration/login.html')

def logoutUser(request):
	logout(request)
	return redirect('login')


# class SignupView(CreateView):
#     template_name = "registration/signup.html"
#     form_class = UserCreationForm

#     def get_success_url(self):
#         return reverse("login")

def LandingPageView(request):
    leads = Lead.objects.all()
    total = leads.count()
    date = datetime.date.today()
    context = {
        "leads" : leads,
        "total" : total ,
        "date" : date
    }
    #return HttpResponse("Hello World")
    return render(request,"landing.html", context)


@login_required(login_url='login')
def lead_list(request):
    if request.user.is_staff == True :
        leads = Lead.objects.filter(is_converted=False)
    else:
        agents = request.user.id
        leads = Lead.objects.select_related('agent').filter(agent = agents , is_converted=False)
    if request.method == "POST":
        lead_resource = LeadResource()
        dataset = Dataset()
        new_leads = request.FILES['myfile']

        imported_data = dataset.load(new_leads.read(),format='xlsx')
        for data in imported_data:
            value = Lead(
                data[0],
        		data[1],
        		data[2],
        		data[3],
                data[4],
                data[5],
                data[6],
                data[7],
                data[8],
                data[9],
                data[10],
                data[11],
                data[12]
        		)
            value.save()
            return redirect("/leads")
    context ={
        'leads' : leads
    }
    return render(request, "leads/lead_list.html" , context)


def voice(): 
    r = sr.Recognizer()
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source)
        print("Please say something")
        audio = r.listen(source)
        print("Recognizing Now ")
        try:
            print("You have said \n" + r.recognize_google(audio))
            print("Audio Recorded Successfully \n ")
        except Exception as e:
            print("Error {} : ".format(e) )
        with open("recorded.wav", "wb") as f:
            f.write(audio.get_wav_data())
        
 
if __name__ == "__main__":
    voice()

@login_required(login_url='login')
def lead_detail(request, pk ):
    lead = Lead.objects.get(id=pk)
    y = Lead.objects.filter(id=pk)
    for x in y:
        import datetime
        age = (datetime.datetime.now() - x.date_created.replace(tzinfo=None)).days
    Lead_communication = lead_communication.objects.select_related('lead_id').filter(lead_id= lead).order_by('Date_created')
    Lead_activity = lead_activity.objects.select_related('lead_id').filter(lead_id= lead)
    form = Lead_communication_form()
    cust_form = customer_form()
    lead_activity_form = Lead_activity_form()
    if request.method == "POST":
        form = Lead_communication_form(request.POST)
        lead_activity_form = Lead_activity_form(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.lead_id = lead
            data.save()
            
    if request.method == "POST":
        lead_activity_form = Lead_activity_form(request.POST)
        if lead_activity_form.is_valid():
            data = lead_activity_form.save(commit=False)
            data.lead_id = lead
            data.save()
    
    if request.method == 'POST':
        cstform = customer_form(request.POST)
        leadform = LeadForm(request.POST,instance=lead)
        if cstform.is_valid() and leadform.is_valid():
            data = cstform.save(commit=False)
            data.lead_id = lead
            data.save()
            data1 = leadform.save(commit=False)
            data1.is_converted = True 
            data1.save()
        return redirect('leads:lead-detail', lead.id)
            

 
    context = {
        "lead": lead,
        "Lead_communication" : Lead_communication ,
        "Lead_activity" : Lead_activity ,
        "form" : form ,
        "Lead_activity_form" : lead_activity_form ,
        "age": age,
        'customer_form' : cust_form
    }
    return render(request, "leads/lead_detail.html", context)



@login_required(login_url='login')
def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("/leads")

    context = {
        "form": form
    }
    return render(request, "leads/lead_create.html", context)

@login_required(login_url='login')
def lead_update(request,pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method =="POST":
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("leads:lead-detail" , lead.pk)
    
    context = {
        "form":form,
        "lead":lead
    }
    return render(request, "leads/lead_update.html", context)

@login_required(login_url='login')
@admin_only
def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads/all")


def customer_list(request):
    customers = Customer.objects.all()
    
    context = {
         'customers': customers
    }
    return render(request, "leads/customer_list.html", context)


def customer_comm(request,pk):
    customer = Customer.objects.get(id=pk)
    communications = Customer_communication.objects.filter(customer_id = customer.id)
    form = Customer_communication_form()
    if request.method =="POST":
        form = Customer_communication_form(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.customer_id = customer
            data.save()
            return redirect("leads:customers-comm" , customer.id )
    
    context = {
         'customer': customer,
         'communications': communications,
         'form': form
    }
    return render(request, "leads/cust_comm.html", context)



# class LeadListView(LoginRequiredMixin,ListView):
#     template_name = "leads/lead_list.html"
#     queryset = Lead.objects.all()
#     context_object_name = "leads"

# class LeadDetailView(LoginRequiredMixin,DetailView):
#     template_name = "leads/lead_detail.html"
#     form_class = LeadModelForm
#     queryset = Lead.objects.all()
#     context_object_name = "lead"

#     def get_success_url(self):
#         return reverse("leads:lead-list")

#     def form_valid(self, form):
#         #TODO send email
#         send_mail(
#             subject="A lead has been created",
#             message="Go to the site to check the new lead",
#             from_email="test@test.com", recipient_list=["test2@test.com"]

# #         )
#         return super(LeadDetailView,self).form_valid(form)
    #queryset = Lead.objects.all()
    #
    

# class LeadCreateView(LoginRequiredMixin,CreateView):
#     template_name = "leads/lead_create.html"
#     form_class = LeadModelForm

#     def get_success_url(self):
#         return reverse("leads:lead-list")

#     def form_valid(self, form):
#         #TODO send email
#         send_mail(
#             subject="A lead has been created",
#             message="Go to the site to check the new lead",
#             from_email="test@test.com", recipient_list=["test2@test.com"]

#         )
#         return super(LeadCreateView,self).form_valid(form)


# class LeadUpdateView(LoginRequiredMixin,UpdateView):
#     template_name = "leads/lead_update.html"
#     queryset = Lead.objects.all()
#     form_class = LeadModelForm

#     def get_success_url(self):

leads/templates/leads/lead_delete.html
{% extends "base.html" %}

{% block content %}
    <a href="{$ url 'leads:lead-list' %}">Go back to leads</a>
    <h1>Are you sure about the delete</h1>

        <form method="delete" action=".">
            {% csrf_token %}
            <button type="submit">Submit</button>
        </form>
        
    </body>
{% endblock %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}
<style>
      .sidenav {
        height: 100%;
        width: 400px;
        position: fixed;
        text-align: center;
        z-index: 1;
        top: 0px;
        left: 0px;
        background: #eee;
        overflow-x: hidden;
        padding-top: 100px;
        background: linear-gradient(359.99deg, rgba(160, 70, 240, 0.348) 9.51%, rgba(251, 199, 212, 0.378) 107.37%);
        box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.25);
      }
      
      .sidenav h1{
        position: relative;
        top:180px;
        font-family: 'Inter';
        font-style: normal;
        font-weight: 600;
        font-size: 35px;
        line-height: 4px;
        color: #000000;
      }
      .sidenav i {
        padding: 6px 1px 4px 10px;
        position: relative;
        top: 190px;
        font-weight: 400;
        font-size: 35px;
        font-size: 25px;
        display: block;
        color: #00000;
      }
      .main-profile-img {
        position: absolute;
        left: 120px;
        top: 95px; 
        width: 150px;
        height: 150px;
        border-radius: 50%;
        border-style: solid;
        border-color: #FFFFFF;
        box-shadow: 0 0 8px 3px #B8B8B8;
    }
    .edit{
      position: absolute;
      left: 220px;
      top: 100px;
      border-radius: 50%;
      border-style: solid; 
      width: 30px;
      height: 30px;
    }

      .main {
        margin-right: 400px;
        font-size: 25px;
        padding: 10px 0px;
      }
      div.content {
        
        margin-left: 450px;
        padding: 0px 0px;
        height: 1000px;
      } 

    .collapsible {
      width: 700px;
      height: 50px;
      background: #8E7FFE;
      border-radius: 11px;
      color: white;
      cursor: pointer;
      padding: 18px 20px;
      border: none;
      text-align: left;
      outline: none;
      font-family: 'Inter';
      font-style: normal;
      font-weight: 700;
      font-size: 25px;
      line-height: 9px;
    }
    
    .active, .collapsible:hover {
      background-color: #23BB86;
    }
    
    .collapsible:after {
      content: '\002B';
      color: white;
      font-weight: bold;
      float: right;
      margin-left: 5px;
    }
    
    .active:after {
      content: "\2212";
    }
    
    .content2 {
      padding: 0 18px;
      max-height: 0;
      overflow: hidden;
      transition: max-height 0.2s ease-out;
      width: 700px;
      display:flex;
      flex: 1 1 auto;
      left: 600px;
      top: 464px;
      background: rgba(142, 127, 254, 0.34);
    }
    .left-half {
      flex: 1;
      display: flex;
      text-overflow: hidden;
    }
    
    .right-half {
      flex: 1 ;
      font-family: 'Inter';
      font-style: normal;
      display: flex;
      text-overflow: hidden;
    }
    .box{
      display: flex;
      text-overflow: hidden;
      padding: 10px;
      background: #F5F5F5;
      border-radius: 20px;
      box-shadow: inset 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    .com{
      font-family: 'Inter';
      font-style: normal;
      font-weight: 700;
      font-size: 30px;
      line-height: 60px;
      color: #7F71EA;
    }
    .btn {
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 12px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 20px;
      margin: 3px 2px;
      transition-duration: 0.4s;
      cursor: pointer;
      background-color: white; 
      color: black; 
      border: 2px solid #8E7FFE;;
      border-radius: 12px;
    }
       
    .btn:hover {
      background-color: #4CAF50;
      color: white;
    }
    .popup {
      display: none;
      position: fixed;
      z-index: 1;
      left: 0;
      top: 0;
      width: 100%;
      height: 100%;
      overflow: auto;
      background-color: rgba(0, 0, 0, 0.5);
    }
    .popup::-webkit-scrollbar {
      display: none;  
    }
    .popup::-webkit-scrollbar-thumb {
      display: none;
    }
    .popup::-webkit-scrollbar-track {
      display:none;
    }
    
    .popup-content {
      background-color: #fefefe;
      margin: 7% auto;
      padding: 20px;
      border: 1px solid #888;
      width: 50%;
      text-align: left;
    }
    
    .close {
      color: #aaa;
      float: right;
      font-size: 28px;
      font-weight: bold;
    }
    
    .close:hover,
    .close:focus {
      color: #000;
      text-decoration: none;
      cursor: pointer;
    }    
    .button1:hover {
      background-color: #4CAF50;
      color: white;
    }
    .button1 {
      background-color: white;
      color: black; 
      border: 2px solid #4CAF50;
      border-radius: 10px;
      padding: 8px 30px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin-top: 5px;
      margin-left: 1120px;
      transition-duration: 0.4s;
      cursor: pointer;
    }
</style>
<link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<body>
  <!-- Sidebar -->
  <div class="sidenav">
    <img src="https://cdn-icons-png.flaticon.com/512/147/147142.png" class="main-profile-img">
    <a href="{% url 'leads:lead-update' lead.pk %}"><img class="edit"src="https://cdn0.iconfinder.com/data/icons/social-messaging-ui-color-shapes/128/write-circle-green-512.png"></img></a>
    <div>
      <h1>{{ lead.first_name }} {{lead.last_name}}</h1>
      <i>Location: {{lead.location}},{{lead.pincode}}</i>
      <i>{{lead.email}}</i>
      <i>{{lead.phone_number}}</i>
      <i>lead designation: {{lead.designation}}</i>
      <i>Lead stage: {{lead.stage}}</i>
      <i>Lead age: {{age}} days</i>
      <i>Lead size: {{lead.size}}</i>
      <i><button style ="color: #FFFFFF;width: 150px;height: 50px;background: black;border-radius: 5px;" onclick='openPopup()'>convert</button></i>
    </div>
  </div>
  <div class="main">
      <div class="content">
        <h1><b>Previous Interactions</b></h1><br>
        {% for i in Lead_communication reversed %}  
        <div style="padding: 15px;">
          <button class="collapsible">Date : {{i.Date_created}}</button>
          <div class="content2">
            {% comment %} <div class="left-half">
              Type : {{i.Type}}<br>
              Proablity:{{i.proablity}}
            </div> {% endcomment %}
            <div>
              Message :{{i.message}}
            </div><hr>
          </div>
        </div>
        {% endfor %}
        {% comment %} <form method="post" action=".">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" id ="btn2">Submit</button><br> 
        </form>  
        <div>
          <i>Demo:</i>
          <input type="checkbox" id="check"><br><br></input>
          <a href="{% url 'leads:lead-demo' lead.pk %}">
            <button disabled="true" id="btn">Shedule</button>
          </a>
        </div> {% endcomment %}
        <div>
          <button class="btn" onclick="showForm(1)">Communication</button>
          <button class="btn" onclick="showForm(2)">Activity</button>
          <form method="post" id="form1">
            {%csrf_token%}
            <div>
              {% comment %} {{form.lead_id}} {% endcomment %}
              {% comment %} <lable class="com">Type : </lable>
              {{ form.Type }}
              <lable class="com">Proablity : </lable>
              {{ form.proablity }} {% endcomment %}
              <lable class="com">Message : </lable>
              {{ form.message }}
              <button type="submit" style ="color: #FFFFFF;width: 250px;height: 50px;background: #23BB86;border-radius: 5px;" >Submit</button>
            </div> 
          </form>
          <form method="post" id="form2">
            {%csrf_token%}
            <div>
              {% comment %} {{Lead_activity_form.lead_id}} {% endcomment %}
              <lable class="com">Sheduled date : </lable>
              {{Lead_activity_form.scheduled_date }}
              <lable class="com">Actual date : </lable>
              {{ Lead_activity_form.actual_date }}
              <lable class="com">Activity : </lable>
              {{Lead_activity_form.activity_name}}</br>
              <lable class="com">Status : </lable>
              {{Lead_activity_form.demo_status}}
              <button type="submit" style ="color: #FFFFFF;width: 250px;height: 50px;background: #23BB86;border-radius: 5px;" >Submit</button>
            </div> 
          </form>
        <div>
          <a href="{% url 'leads:lead-list' %}" style="color: #7F71EA;"><i class="fa-solid fa-angle-left"></i>  Go back to leads</a><br>
          {% comment %} <a style="color: #F53838; position: relative; bottom: 0px; left: 500px" href="{% url 'leads:lead-delete' lead.pk %}">
            <i class="fa-solid fa-trash-can" ></i>Delete
          </a><br> {% endcomment %}
          <a style="color: #F53838;" href="{% url 'leads:help' lead.pk %}">
            <button><i class="fa-solid fa-download"></i>Generate Quoation</button></a>
          {% comment %} </a><br>
          <a style="color: #F53838;" href="{% url 'leads:sendEmail' lead.pk %}">
            <i class="fa-solid fa-paper-plane"></i>send email
          </a><br> {% endcomment %}
        </div>
      </div>
      </div>
  </div>
  <div id="popup" class="popup">
    <div class="popup-content">
      <span class="close" onclick="closePopup()">&times;</span>
      <h1 style='font-family:"Calibri", sans-serif;font-size: 20px'><u>Customer Details</u></h1>
      <form method="POST" action="{% url 'leads:lead-detail' lead.id %}">
      {% csrf_token %}
      {{ customer_form.as_p }}
      <input class='button' type="submit" value="Save">
      </form>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" ></script>
  <script type="text/javascript">
        {% comment %} $(document).ready(function(){
          var a = JSON.parse("{{ lead.pk|escapejs }}");
          $("#lead_id").val(a);
        }); 
        $(document).ready(function(){
          var a = JSON.parse("{{ lead.pk|escapejs }}");
          $("#activity_id").val(a);
        });  {% endcomment %}
       {% comment %} $(document).ready(function(){
          $("#check").on("change",function(){
            var checVal = $("#check").val();
            if($("#check").is(":checked")){
              $("#btn").attr("disabled",false);
            }
            else{
              $("#btn").attr("disabled",true);
            }
          });
        }); {% endcomment %}
        var coll = document.getElementsByClassName("collapsible");
        var i;
        
        for (i = 0; i < coll.length; i++) {
          coll[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.maxHeight){
              content.style.maxHeight = null;
            } else {
              content.style.maxHeight = content.scrollHeight + "px";
            } 
          });
        }
        var form1 = document.getElementById('form1');
        var form2 = document.getElementById('form2');
        form2.style.display = "none";
        form1.style.display = "block";

        function showForm(x){
        if(x==1){ /* Check what form should be shown */
        form1.style.display = "block";
        form2.style.display = "none";
        }else if(x==2) {
        form1.style.display = "none";
        form2.style.display = "block";
        }
        };
        function openPopup() {
          document.getElementById("popup").style.display = "block";
        }
        
        function closePopup() {
          document.getElementById("popup").style.display = "none";
        }
        {% comment %} $(document).ready(function(){
          $("#btn2").click(function(){
            var inputval = $("#proablity").val();
            if($("#proablity").val()== 100){
              alert("Submited successfully . Please schedule Demo.");
            }
            else{
              alert("Are you sure to submit?");
            }
          });
        }); {% endcomment %}
  </script>
</body>

        
       
{% endblock %}

leads/templates/leads/sendemail.html
{% extends 'base.html' %}

{% block content %}
<style>
    h1{
        font-family: 'Inter';
        font-style: normal;
        font-weight: 600;
        font-size: 35px;
        line-height: 4px;
        color: #000000;
    }
</style>
<div class="info">
    <div class="container" style="text-align:center;">
        <h1>Email Sent</h1><br>
        <a href="{% url 'leads:lead-list' %}" style="color: #7F71EA;">Go back to leads</a>
    </div>
</div>
{% endblock %}