agents/urls.py
from django.urls import URLPattern

from django.urls import path
from .views import  AgentCreateView , agent_list , agentdetail

app_name = 'agents'

urlpatterns = [
    path('', agent_list , name='agent-list'),
    path('<int:pk>/', agentdetail, name='agent-detail'),
    # path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
#    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='Agent-delete'),
    path('create/',AgentCreateView, name='agent-create')
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path, include
from leads.views import LandingPageView,registerPage ,loginPage , logoutUser 
from agents.views import  dashboard , agentdashboard ,configuration




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView, name='landing-page'),
    path('dashboard/', dashboard , name='dashboard'),
    path('agentdashboard/', agentdashboard , name='agent-dashboard'),
    path('config/', configuration , name='config'),
    path('leads/', include(('leads.urls','leads'),namespace="leads")),
    path('agents/',include(('agents.urls','agents'),namespace="agents")),
    path('signup/',registerPage, name='signup'),
    path('login/', loginPage,name='login'),
    path('logout/', logoutUser,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import customer_comm, customer_list, lead_list, lead_detail,lead_create,lead_update,lead_create,lead_update , lead_delete 
from .helpers.pdf import GeneratePdf ,helper
from .helpers.email import  send_my_mail

from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib import admin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_names = "leads"

urlpatterns = [
    path('', lead_list, name='lead-list'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/genratequoation/',GeneratePdf.as_view(), name='pdf'),
    path('<int:pk>/helper/', helper , name='help'),
    path('<int:pk>/delete/', lead_delete , name='lead-delete'),
    path('<int:pk>/email', send_my_mail, name='sendEmail'),
    path('create/',lead_create, name='lead-create'),
    path('cust', customer_list , name='customers-list'),
    path('<int:pk>/cust_comm', customer_comm , name='customers-comm'),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL ,document_root = settings.STATIC_ROOT)

agents/models.py
from django.db import models
from django.contrib.auth.models import User , Group


class agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE , primary_key=True)
    agent_name = models.CharField(max_length = 20)
    organisation = models.CharField(max_length = 30 )
    phone_number = models.CharField(max_length=10)
    email = models.EmailField(null=True, max_length=50)

    def __str__(self):
        return f"{self.agent_name}"
    

agents/forms.py
from django import forms
from .models import agent


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = agent
        fields = (
            'user',
            'agent_name',
            'organisation',
            'phone_number',
            'email',
        )
        widgets = { 
            'user' : forms.Select(choices=['test'] ,attrs={'class':'box', 'style':'top: 220px; left: 100px;'}),
            'agent_name': forms.TextInput(attrs={'class':"box" , 'style':'left: 100px; top: 310px;'}),
            'organisation': forms.TextInput(attrs={'class':"box" , 'style':'left: 100px; top: 400px;'}),
            'phone_number' : forms.NumberInput(attrs={'class':"box" , 'style':'left: 100px; top: 490px;'}),
            'email': forms.TextInput(attrs={'class':"box" , 'style':'left: 100px;top: 580px;'}),
        }


class agentupdateform(forms.ModelForm):
    class Meta:
        model = agent
        fields = (
            'user',
            'agent_name',
            'organisation',
            'phone_number',
            'email',
        )
        widgets = {
            'user' : forms.HiddenInput(attrs={'id' : 'agent_id'}),
            'email' : forms.EmailInput(attrs={'class':"box" , 'style':'left: 100px; top: 490px;'}),
            'agent_name' : forms.TextInput(attrs={'class':'box', 'style':'top: 220px; left: 101px;'}),
            'organisation': forms.TextInput(attrs={'class':"box" , 'style':'left: 100px; top: 310px;'}),
            'phone_number': forms.NumberInput(attrs={'class':"box" , 'style':'left: 100px; top: 400px;'}),
        }

agents/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, reverse 
# Create your views here.
from urllib.parse import _NetlocResultMixinStr
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
# from leads.models import Agent
from .forms import AgentModelForm , agentupdateform
from .models import agent
from django.contrib.auth.decorators import login_required
from leads.models import Lead , lead_activity
import datetime
from leads.decorators import unauthenticated_user, allowed_users, admin_only
from datetime import timedelta
# Create your views here.
@login_required(login_url='login')
@admin_only
def agent_list(request):
    agents = agent.objects.all()
    context = {
        "agents" : agents
    }
    return render(request,"agents/agent_list.html", context)
    # def get_queryset(self):
    #     organisation = self.request.user.userprofile
    #     return Agent.objects.filter(organisation=organisation)
@login_required(login_url='login')
@admin_only
def AgentCreateView(request):
    form =  AgentModelForm()
    if request.method == "POST":
        form = AgentModelForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("agents:agent-list")
    context = {
        "form": form
    }
    return render(request, "agents/agent_create.html", context)


@login_required(login_url='login')
@admin_only
def agentdetail(request,pk):
    agents = agent.objects.get(user_id=pk)
    form = agentupdateform(instance=agents)
    if request.method =="POST":
        form = agentupdateform(request.POST, instance=agents)
        if form.is_valid():
            form.save()
            return redirect("agents:agent-list")
    context = {
        "form":form,
        "agents" : agents
    }
    return render(request, "agents/agent_detail.html", context)



@login_required(login_url='login')
@admin_only
def dashboard(request):
    leads = Lead.objects.all()
    t_date=datetime.date.today()
    date_entry = ()
    query = request.GET.get('search')
    try:
        date_entry = query
        year, month, day = map(int, date_entry.split('-'))
        date = datetime.date(year, month, day)
    except:
        date=datetime.date.today()


    if request.method == 'GET':
        a = request.GET.get("stats")
        if a == "daily" :
            total = Lead.objects.filter(date_created__gte=datetime.datetime.now()-timedelta(days=1)).count()
        elif a == "week" :
            total = Lead.objects.filter(date_created__gte=datetime.datetime.now()-timedelta(days=7)).count()
        elif a == "month" :
            total = Lead.objects.filter(date_created__gte=datetime.datetime.now()-timedelta(days=30)).count()
        elif a == "year" :
            total = Lead.objects.filter(date_created__gte=datetime.datetime.now()-timedelta(days=365)).count()
        else:
            total = leads.count()
    activity = lead_activity.objects.select_related('lead_id').filter(scheduled_date = date)
    today_activity = lead_activity.objects.select_related('lead_id').filter(scheduled_date = t_date)
    activitytotal = today_activity.count()
    context = {
        "leads" : leads,
        "total" : total ,
        "date" : date,
        "activity" : activity ,
        "activitytotal" : activitytotal,
        't_date' : t_date
    }
    return render(request,"dashboard.html", context)



def agentdashboard(request):
    date_entry = ()
    query = request.GET.get('search')
    try:
        date_entry = query
        year, month, day = map(int, date_entry.split('-'))
        date = datetime.date(year, month, day)
    except:
        date=datetime.date.today()
    t_date=datetime.date.today()
    agents = request.user.id
    leads = Lead.objects.filter(agent = agents)
    activity_list = []
    activity_today = []
    for lead_id in leads:
        for lead_activity_obj in lead_activity.objects.filter(lead_id=lead_id,scheduled_date=date):
            activity_list.append(lead_activity_obj)
        for lead_activity_obj in lead_activity.objects.filter(lead_id=lead_id,scheduled_date=t_date):
           activity_today.append(lead_activity_obj)
    if request.method == 'GET':
        a = request.GET.get("stats")
        if a == "daily" :
            total = Lead.objects.filter(agent = agents,date_created__gte=datetime.datetime.now()-timedelta(days=1)).count()
        elif a == "week" :
            total = Lead.objects.filter(agent = agents,date_created__gte=datetime.datetime.now()-timedelta(days=7)).count()
        elif a == "month" :
            total = Lead.objects.filter(agent = agents,date_created__gte=datetime.datetime.now()-timedelta(days=30)).count()
        elif a == "year" :
            total = Lead.objects.filter(agent = agents,date_created__gte=datetime.datetime.now()-timedelta(days=365)).count()
        else:
            total = leads.count()
    activitytotal = len(activity_today)

    context = {
        "leads": leads,
        "total" : total ,
        "date" : date ,
        "activity" : activity_list ,
        "activitytotal" : activitytotal,
        't_date' : t_date
    }
    return render(request, "agentdashboard.html", context)



def configuration(request):
    leads = Lead.objects.all()
    date = datetime.date.today()
    context = {
        "leads" : leads,
        "date" : date
    }
    return render(request,"agents/configuration.html", context)

# class AgentUpdateView(LoginRequiredMixin, generic.TemplateView):
#     template_name = "agents/agent_update.html"
#     form_class = AgentModelForm

#     def get_success_url(self):
#         return reverse("agents:agent-list")

agents/templates/agents/agent_create.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
  page{position: relative;
  width: 1440px;
  height: 1300px;
  background: #FFFFFF;
  }
  .box{
      box-sizing: border-box;
      position: absolute;
      width: 428px;
      height: 50px;
      border-style: outset;
      border: 2px solid #D9D9D9;
      border-radius: 8px;
  }
  .head{
      position: absolute;
      width: 211px;
      height: 48px;
      left: 110px;
      top: 100px;
      font-weight: 700;
      font-size: 33px;
      line-height: 48px;
      text-align: center;
      color: #7F71EA;
  }
  .btn{
      position: absolute;
      width: 300px;
      height: 50px;
      left: 1000px;
      top: 600px;
      background: #8E7FFE;
      color: #FFFFFF;
      border-radius: 10px;
      
  }
  .name{
      position: absolute;
      width: 180px;
      height: 29px;
      font-weight: 600;
      font-size: 20px;
      line-height: 24px;
      color: #8E7FFE;
  }
  .icon{
      position: absolute;
      vertical-align: middle;
      width: 50px;
      height: 50px;
      left: 110px;
      top: 100px;
      border-radius: 50%;
  }
  .btn2{
    position: absolute;
    left: 1033px;
    top: 100px;
    color: #7F71EA;
    cursor: pointer;
  }
</style>
<body class="page">
  <h1 class="head">AGENT</h1>
  <img class="icon" src="https://thumbs.dreamstime.com/b/salesman-salesman-icon-147167439.jpg"></img>
  <form method="post" action=".">
    {% csrf_token %}
    <div>
        <lable class="name" style="left: 100px; top: 170px;">User id :</lable>
        {{ form.user }}
        <lable class="name" style="left: 100px; top: 280px;" >Name : </lable>
        {{ form.agent_name }} 
        <lable class="name" style="left: 100px; top: 370px;">Organisation : </lable>
        {{ form.organisation }}
        <lable class="name" style="left: 100px; top: 460px;">Phone Number : </lable>
        {{ form.phone_number }}
        <lable class="name" style="left: 100px; top: 550px;">Email : </lable>
        {{ form.email }}
    </div>
    <button class="btn" type="submit"></i>Save</button>  
    <a href="{% url 'agents:agent-list' %}" class="btn2"><i class="fa-solid fa-angle-left"></i>  Go back to agents</a>
  </form>
</body>     
{% endblock %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
  page{position: relative;
  width: 1440px;
  height: 1300px;
  background: #FFFFFF;
  }
  .box{
      box-sizing: border-box;
      position: absolute;
      width: 428px;
      height: 50px;
      border-style: outset;
      border: 2px solid #D9D9D9;
      border-radius: 8px;
  }
  .head{
      position: absolute;
      width: 211px;
      height: 48px;
      left: 110px;
      top: 100px;
      font-weight: 700;
      font-size: 33px;
      line-height: 48px;
      text-align: center;
      color: #7F71EA;
  }
  .btn{
      position: absolute;
      width: 300px;
      height: 50px;
      left: 1000px;
      top: 600px;
      background: #8E7FFE;
      color: #FFFFFF;
      border-radius: 10px;
      
  }
  .name{
      position: absolute;
      width: 180px;
      height: 29px;
      font-weight: 600;
      font-size: 20px;
      line-height: 24px;
      color: #8E7FFE;
  }
  .icon{
      position: absolute;
      vertical-align: middle;
      width: 50px;
      height: 50px;
      left: 110px;
      top: 100px;
      border-radius: 50%;
  }
  .btn2{
    position: absolute;
    left: 1033px;
    top: 100px;
    color: #7F71EA;
    cursor: pointer;
  }
</style>
<body class="page">
  <h1 class="head">AGENT</h1>
  <img class="icon" src="https://thumbs.dreamstime.com/b/salesman-salesman-icon-147167439.jpg"></img>
  <form method="post" action=".">
    {% csrf_token %}
    <div>
      {{form.user}}
        <lable class="name" style="left: 100px; top: 170px;">Name : </lable>
        {{ form.agent_name }}
        <lable class="name" style="left: 100px; top: 280px;" >Organisation : </lable>
        {{ form.organisation }} 
        <lable class="name" style="left: 100px; top: 370px;">Phone Number : </lable>
        {{ form.phone_number }}
        <lable class="name" style="left: 100px; top: 460px;">Email : </lable>
        {{ form.email }}
    </div>
    <button class="btn" type="submit"></i>Save</button>  
    <a href="{% url 'agents:agent-list' %}" class="btn2"><i class="fa-solid fa-angle-left"></i>  Go back to agents</a>
  </form>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" ></script>
<script type="text/javascript">
  $(document).ready(function(){
    var a = JSON.parse("{{ agents.pk|escapejs }}");
    $("#agent_id").val(a);
    /*$("#lead_id").attr("disabled",true);*/
  }); 
</script>      
{% endblock %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}
<link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<section class="text-gray-700 body-font bgcolor" >
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200" >
            <div>
                <h1 style="color: #000000;font-weight: 600;font-size: 40px;line-height: 48px;">AGENTS</h1>
            </div>
            <div>
                <a style="color: #8272F5;" href="{% url 'agents:agent-create' %}">
                  <i class="fas fa-plus"></i>
                  Create a new agent
                </a>
            </div>
        </div>
      <div class="flex flex-wrap -m-4">
        {% for agent in agents %}
        <div class="p-4 lg:w-1/2 md:w-full">
            <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"style="background: #8E7FFE;box-shadow: 0px 10px 30px rgba(54, 159, 255, 0.4);border-radius: 20px;width: 400px;height: 135px;">
                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                  <img src="https://cdn.iconscout.com/icon/free/png-128/agent-broker-real-estate-rate-rent-home-house-3-11963.png" style="border-radius: 50%;"></img>
                </div>
                <div class="flex-grow">
                  <h2 style="font-weight: 500;font-size: 28px;color: #FFFFFF;">
                    {{ agent.agent_name }}</h2>
                  <a class="mt-3 text-indigo-500 inline-flex items-center">
                    <a href="{% url 'agents:agent-detail' agent.pk %}" style="color: #FFFFFF;">View this Agent <i class="fa-solid fa-arrow-right"></i></a>
                  </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>
</section>
        
        
{% endblock %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }} </h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Description</a>
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Reviews</a>
            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Details</a>
          </div>
          <form method="post" action=".">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
          </form>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
        
        <a href="{% url 'agents:agent-list' %}">Go back to leads</a>

        
        
        
{% endblock %}

agents/templates/agents/configuration.html
{% extends 'base.html'  %}

{% block  content %}
<style>
    .btn {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 30px 30px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 20px;
        margin: 4px 10px;
        transition-duration: 0.4s;
        cursor: pointer;
        background-color: white; 
        color: black; 
        border: 2px solid #8E7FFE;
        border-radius: 12px;
      }
      .btn:hover {
        background-color: #4CAF50;
        color: white;
      }
</style>
<body>
    <a class="btn" href="{% url 'agents:agent-list' %}">Agents</a>
    <a class="btn" href="{% url 'leads:customers-list' %}">Customers</a>
    <button class="btn">Product</button>
  </body>
  {% endblock content %}