crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path, include
from leads.views import LandingPageView,registerPage ,loginPage , logoutUser 
from agents.views import  dashboard , agentdashboard ,configuration




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView, name='landing-page'),
    path('dashboard/', dashboard , name='dashboard'),
    path('agentdashboard/', agentdashboard , name='agent-dashboard'),
    path('config/', configuration , name='config'),
    path('leads/', include(('leads.urls','leads'),namespace="leads")),
    path('agents/',include(('agents.urls','agents'),namespace="agents")),
    path('signup/',registerPage, name='signup'),
    path('login/', loginPage,name='login'),
    path('logout/', logoutUser,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import customer_comm, customer_list, lead_list, lead_detail,lead_create,lead_update,lead_create,lead_update , lead_delete 
from .helpers.pdf import GeneratePdf ,helper
from .helpers.email import  send_my_mail

from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib import admin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

app_names = "leads"

urlpatterns = [
    path('', lead_list, name='lead-list'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/genratequoation/',GeneratePdf.as_view(), name='pdf'),
    path('<int:pk>/helper/', helper , name='help'),
    path('<int:pk>/delete/', lead_delete , name='lead-delete'),
    path('<int:pk>/email', send_my_mail, name='sendEmail'),
    path('create/',lead_create, name='lead-create'),
    path('cust', customer_list , name='customers-list'),
    path('<int:pk>/cust_comm', customer_comm , name='customers-comm'),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL ,document_root = settings.STATIC_ROOT)

templates/agentdashboard.html
{% extends 'base.html'  %}

{% block  content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<style>
  .page{
    position: relative;
    width: 100%;
    height: 100%;
    background: #FFFFFF;
  }
  .head{
        font-weight: 500;
        font-size: 50px;
        line-height: 70px;
        display: flex;
        align-items: center;
        line-height: 1em;
        color: #000000;
  }
  .rightbox {
    height: 100%;
    width: 500px;
    position: fixed;
    z-index: 1;
    top: 140px;
    right: 10px;
    overflow-x: hidden;
    padding-top: 100px;
  }
  .rightbox h1 {
    position: absolute;
    top: 0px;
    font-weight: 500;
    font-size: 18px;
    line-height: 22px;   
    color: #8E7FFE
  }
</style>
<link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<div>
  <h1 class="head">ENGINEERING INNOVATION</h1>
  <div class="head" style="font-size: 40px;color: #485FE5;">
    <p>MADE EASY WITH</p>
  </div>
  <p class="head" style="color: #485FE5;"><b>CRM</b></p><br>
  <div>
    <form id="form" method="GET" action="#" style=>
      <select style="font-weight: 400;font-size: 24px;line-height: 29px;background: rgba(142, 127, 254, 0.92);box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);border-radius: 5px;color: #F1F5F9;" name="stats" id="stats">
        <option value="week">Weekly</option>
        <option value="daily">Daily</option>
        <option value="month">Monthly</option>
        <option value="year">Yearly</option>
      </select>
    </form>
    <div>
      <h2 style="text-transform: uppercase;color: #FF5B5A;">LEADS</h2>
      <p style="font-weight: 600;font-size: 45px;color: #454256;">{{total}}</p>
    </div>
    <div style="position: absolute;left: 350px;top: 272px;">
      <p style="color: #FF5B5A;">ACTIVITYS TODAY</p>
      <p style="font-weight: 600;font-size: 45px;color: #454256;">{{activitytotal}}</p>
    </div>
  </div>
  <canvas id="myChart" style="top: 50px; width:100%;max-width:500px;"></canvas>
</div>
<div class = "rightbox">
  <h1>Activitys</h1>
  <form style="position: absolute;top: 50px;" method="GET" action="" id="my_form" >
    <input type="date" name="search" id='check' style="background: rgba(142, 127, 254, 0.92);box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);border-radius: 5px;"/>
    {% comment %} <i class="fa-solid fa-calendar-days"></i> {% endcomment %}
  </form>
  <h2 style="position: absolute;top: 25px;">Date : {{t_date}}</h2>
    {% for i in activity %}
    <div style="padding: 10px;">
      <div style="width: 350px;height: 105px;background: #8E7FFE;border-radius: 10px;"><a href="{% url 'leads:lead-detail' i.lead_id %}" style="color: #FFFFFF;">
        <h2 style="font-weight: 600; font-size: 20px;color: #FFFFFF;position:relative; left:30px; top: 10px;">
          {{ i.lead_id.first_name }} {{i.lead_id.last_name}}
        </h2>
        <p style="color: #FFFFFF;position:relative; left:30px;top: 10px;">Activity : {{i.activity_name}}</p>
        <p style="color: #FFFFFF;position:relative; left:30px;top: 10px;">Agent : {{i.lead_id.agent}}</p></a>
      </div>
    </div>
    {% endfor %}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" ></script>
<script type="text/javascript">
  var xValues = ["Jan", "Feb", "Mar", "Apr", "May" ,"Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"];
  var yValues = [100, 200, 300, 400, 500 , 600 , 700 , 800 , 900 ,1000 , 1100 , 1200];
  var barColors = ["red", "green","blue","#33cc33","#4A52FF" , "#58CEFF" , "#b91d47","#AB53DB","#2b5797","#FF5B5A"," #FFBC54" , "#00A28A"];
  
  new Chart("myChart", {
    type: "bar",
    data: {
      labels: xValues,
      datasets: [{
        backgroundColor: barColors,
        data: yValues
      }]
    },
    options: {
      legend: {display: false},
      title: {
        display: true,
        text: "Monthly Visitors"
      }
    }
  });
  $(document).ready(function(){
    $("#check").on("change",function(){
    var form = document.getElementById("my_form");
    form.submit();
  });});
  $(document).ready(function(){
    $("#stats").on("change",function(){
    var form = document.getElementById("form");
    form.submit();
    });
  });
  </script>
  {% endblock content %}
  

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>CRM</title>
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body>
        
        <div class="max-w-7xl mx-auto">
           
            {% include 'navbar.html' %}
            {% block content %}
            {% endblock content %}
            {% include "script.html" %}
            
        </div>
           
    </body>
  
</html>

templates/dashboard.html
{% extends 'base.html'  %}

{% block  content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<style>
  .page{
    position: relative;
    width: 100%;
    height: 100%;
    background: #FFFFFF;
  }
  .head{
        font-weight: 500;
        font-size: 50px;
        line-height: 70px;
        display: flex;
        align-items: center;
        line-height: 1em;
        color: #000000;
  }
  .rightbox {
    height: 100%;
    width: 500px;
    position: fixed;
    z-index: 1;
    top: 140px;
    right: 10px;
    overflow-x: hidden;
    padding-top: 100px;
  }
  .rightbox h1 {
    position: absolute;
    top: 0px;
    font-weight: 500;
    font-size: 18px;
    line-height: 22px;   
    color: #8E7FFE
  }
</style>
<link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<div>
  <h1 class="head">ENGINEERING INNOVATION</h1>
  <div class="head" style="font-size: 40px;color: #485FE5;">
    <p>MADE EASY WITH</p>
  </div>
  <p class="head" style="color: #485FE5;"><b>CRM</b></p><br>
  <div>
    <form id="form" method="GET" action="#" style=>
      <select style="font-weight: 400;font-size: 24px;line-height: 29px;background: rgba(142, 127, 254, 0.92);box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);border-radius: 5px;color: #F1F5F9;" name="stats" id="stats">
        <option value="week">Weekly</option>
        <option value="daily">Daily</option>
        <option value="month">Monthly</option>
        <option value="year">Yearly</option>
      </select>
    </form>
    <div>
      <h2 style="text-transform: uppercase;color: #FF5B5A;">LEADS</h2>
      <p style="font-weight: 600;font-size: 45px;color: #454256;">{{total}}</p>
    </div>
    <div style="position: absolute;left: 350px;top: 272px;">
      <p style="color: #FF5B5A;">ACTIVITYS TODAY</p>
      <p style="font-weight: 600;font-size: 45px;color: #454256;">{{activitytotal}}</p>
    </div>
  </div>
  <canvas id="myChart" style="top: 50px; width:100%;max-width:500px;"></canvas>
</div>
<div class = "rightbox">
  <h1>Activitys</h1>
  <form style="position: absolute;top: 50px;" method="GET" action="" id="my_form" >
    <input type="date" name="search" id='check' style="background: rgba(142, 127, 254, 0.92);box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);border-radius: 5px;"/>
    {% comment %} <i class="fa-solid fa-calendar-days"></i> {% endcomment %}
  </form>
  <h2 style="position: absolute;top: 25px;">Date : {{t_date}}</h2>
    {% for i in activity %}
    <div style="padding: 10px;">
      <div style="width: 350px;height: 105px;background: #8E7FFE;border-radius: 10px;"><a href="{% url 'leads:lead-detail' i.lead_id %}" style="color: #FFFFFF;">
        <h2 style="font-weight: 600; font-size: 20px;color: #FFFFFF;position:relative; left:30px; top: 10px;">
          {{ i.lead_id.first_name }} {{i.lead_id.last_name}}
        </h2>
        <p style="color: #FFFFFF;position:relative; left:30px;top: 10px;">Activity : {{i.activity_name}}</p>
        <p style="color: #FFFFFF;position:relative; left:30px;top: 10px;">Agent : {{i.lead_id.agent}}</p></a>
      </div>
    </div>
    {% endfor %}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" ></script>
<script type="text/javascript">
  var xValues = ["Jan", "Feb", "Mar", "Apr", "May" ,"Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"];
  var yValues = [100, 200, 300, 400, 500 , 600 , 700 , 800 , 900 ,1000 , 1100 , 1200];
  var barColors = ["red", "green","blue","#33cc33","#4A52FF" , "#58CEFF" , "#b91d47","#AB53DB","#2b5797","#FF5B5A"," #FFBC54" , "#00A28A"];
  
  new Chart("myChart", {
    type: "bar",
    data: {
      labels: xValues,
      datasets: [{
        backgroundColor: barColors,
        data: yValues
      }]
    },
    options: {
      legend: {display: false},
      title: {
        display: true,
        text: "Monthly Visitors"
      }
    }
  });
  $(document).ready(function(){
    $("#check").on("change",function(){
    var form = document.getElementById("my_form");
    form.submit();
  });});
  $(document).ready(function(){
    $("#stats").on("change",function(){
    var form = document.getElementById("form");
    form.submit();
    });
  });
  </script>
  {% endblock content %}
  

templates/landing.html
{% extends 'base.html'  %}

{% block  content %}
<style>
  {% comment %} *,*:after,*:before{
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    box-sizing: border-box;
}
  body{
    font-family: arial;
    font-size: 16px;
    margin: 0;
    background:linear-gradient(to right bottom, #d13cff, #031f6a);
    color: #000;
    
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
  } {% endcomment %}
</style>
<body>
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" src="https://img.etimg.com/thumb/msid-81773160,width-1070,height-580,imgsize-126697,overlay-etrise/photo.jpg">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900" style="color: #485FE5;"><b>CRM for Small Scale Industries</b></h1>
        <p class="mb-8 leading-relaxed">
            Build your customer relationship with Our CRM.    
        </p>
        <div class="flex justify-center">
        </div>
      </div>
    </div>
  </body>
  {% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      
      {% if not request.user.is_authenticated %}
        <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
      {% else %}
      {% if request.user.is_staff %}
        <a href="{% url 'dashboard' %}" class="mr-5 hover:text-gray-900">Dashboard</a>
        <a href="{% url 'config' %}" class="mr-5 hover:text-gray-900">Configuration</a>
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
      {%else%}
        <a href="{% url 'agent-dashboard' %}" class="mr-5 hover:text-gray-900">Dashboard</a>
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
      {%endif%}
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
      Logged in as: {{ request.user.username }}
      <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Logout
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    {% else %}
    <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
      Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

templates/script.html
{% load static %}

<script src="{% static '/js/main.js' %}"></script>